[package]
name = "circuits"
type = "bin"
authors = ["Satyam Bansal"]

[dependencies]
trees = { git = "https://github.com/privacy-scaling-explorations/zk-kit.noir", tag = "main", directory = "packages/merkle-trees" }
